@baseUrl = http://localhost:3000

### AppControllerGetHello

# @name AppControllerGetHello
GET {{baseUrl}}/home/hello

### AppControllerGetHello

# @name AppControllerGetExemplo
GET {{baseUrl}}/home/exemplo

### ConceitosManualController

# @name ConceitosManualController
GET {{baseUrl}}/conceitos-manual

### ConteitosAutomaticoController

# @name ConteitosAutomaticoController
GET {{baseUrl}}/conteitos-automatico

### ConceitosManualControllerService

# @name ConceitosManualControllerService
GET {{baseUrl}}/conceitos-manual/teste

### RecadosControllerFindAll

# @name RecadosControllerFindAll
GET {{baseUrl}}/recados

### RecadosControllerFindOne

# @name RecadosControllerFindOne
GET {{baseUrl}}/recados/1

### RecadosControllerFindOne

# @name RecadosControllerInsert
POST  {{baseUrl}}/recados
Content-Type: application/json

  {
    "texto": "Novo recado",
    "deId": 4,
    "paraId": 4
  }

### RecadosControllerFindOne

# @name RecadosControllerInsert
PATCH   {{baseUrl}}/recados/1
Content-Type: application/json

  {
    "texto": "esse e um recado de teste atualizado",
    "de": "Joana",
    "para": "joao",
    "lido": false
  }

### RecadosControllerFindOne

# @name RecadosControllerFindOne
DELETE {{baseUrl}}/recados/3


### RecadosControllerFindAll

# @name RecadosControllerFindAll
GET {{baseUrl}}/recados/q
?limit=100
&offset=100

### pessoasControllerFindAll

# @name pessoasControllerFindAll
GET {{baseUrl}}/pessoas

### pessoasControllerFindOne

# @name pessoasControllerFindOne
GET {{baseUrl}}/pessoas/3

### pessoasControllerFindOne

# @name pessoasControllerInsert
POST  {{baseUrl}}/pessoas
Content-Type: application/json

  {
    "email":"teste@teste.com",
    "password":"!1Vbgf",
    "nome":"testae"
  }

### pessoasControllerFindOne

# @name pessoasControllerInsert
PATCH   {{baseUrl}}/pessoas/4
Content-Type: application/json

{
  "password": "!1Vbgf",
  "nome": "teste"
}

### pessoasControllerFindOne

# @name PessoasControllerFindOne
DELETE {{baseUrl}}/pessoas/3


### pessoasControllerFindAll

# @name pessoasControllerFindAll
GET {{baseUrl}}/pessoas/q
?limit=100
&offset=100