@baseUrl = http://localhost:3000

### AppControllerGetHello

# @name AppControllerGetHello
GET {{baseUrl}}/home/hello

### AppControllerGetHello

# @name AppControllerGetExemplo
GET {{baseUrl}}/home/exemplo

### ConceitosManualController

# @name ConceitosManualController
GET {{baseUrl}}/conceitos-manual

### ConteitosAutomaticoController

# @name ConteitosAutomaticoController
GET {{baseUrl}}/conteitos-automatico

### ConceitosManualControllerService

# @name ConceitosManualControllerService
GET {{baseUrl}}/conceitos-manual/teste