version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: curso_nestjs_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: curso_nestjs
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - curso_nestjs_network

networks:
  curso_nestjs_network:
    driver: bridge

volumes:
  postgres_data:
